### PR TITLE
Distill + Distribution with DistROOT

### PR DESCRIPTION
**Pull request by mblaszkiewicz**
Still some errors with the histograms merging, even after adding models (hb_th_x_diffLR and hb_th_y_diffLR) + three histograms commented out: #TODO: TypeError: can not resolve method template call for 'Histo2D'

By the way, we found that selected Histo1D originally were Histo2D, we changed them here, should that be ok?

### CODE REVIEW

**Comment by etejedor** [comment]
`Histo2D(("", "", 64, -4., 4., 64, -4., 4.)` should fix the error you have. The thing to notice is that the min and max for each axis should be doubles

**Comment by mblaszkiewicz** [comment]
Right, we switched now to the models Javier has sent us. There was only this small thing that kept us so long: after # Line 1441 (in reference to the original code), the modelreal was created but never used and this caused errors I mentioned in the last mail. Adding 
```python
model = ROOT.RDF.TH1DModel(modelreal)
bh_t_normalized_ob_1_30_02 = f5.Define("corr_norm", "corr * normalization") \
.Histo1D(model, "k_t", "corr_norm")
```
is enough. @JavierCVilla if you could add this to the distributions.py, we will avoid this in the future!
There are several histograms left at the end, we will fix it in the morning.

**Comment by JavierCVilla** [comment]
@mblaszkiewicz Fixing that, sorry for the inconveniences. 

@etejedor : right, doubles and different from 0, so the range does not have to be deducted.

I'm modifying the code to follow @bluehood's proposal: rather than passing just tuples to `HistoND`, which may produce an unexpected/uncommon behaviour of PyROOT, we can pass the correct type explicitly (`TH1DModel` and `TH2DModel`) which prevents us from that PyROOT behaviour and shows a more intuitive error in case of wrong parameters.

**Comment by mblaszkiewicz** [comment]
@JavierCVilla if you could spare a moment, could you please take a look at the way we save histograms? It's just copied from script (but with a list instead of single variables) and it seems to be not working at all (here in the notebook). Directories are being created but nothing inside them

**Comment by JavierCVilla** [comment]
@mblaszkiewicz sure, I'm trying to run the notebook but it fails when running in Spark.

Could you please share your spark configuration ? I just tried with the default values.

**Comment by mblaszkiewicz** [comment]
I thought that default values we use are saved in the notebook, we have only those:

- spark.executorEnv.KRB5CCNAME
 ./krbcache

- spark.driver.memory
 2g

- spark.executor.instances
 4

- spark.yarn.dist.files {KRB5CCNAME}#krbcache,./DistROOT.py,./common_definitions.h,./common_algorithms.h,./parameters.h,./parameters_global.h,./common.h,./common_cuts.h,./common_parameters.h,./binning/generators.root

- spark.executor.extraLibraryPath
 {LD_LIBRARY_PATH}

Those are for swan.cern.ch; in case you are trying to run it at HN, then spark.executorEnv.KRB5CCNAME and {KRB5CCNAME}#krbcache from spark.yarn.dist.files should be deleted

**Comment by JavierCVilla** [comment]
@mblaszkiewicz I think histograms are correctly saved on disk with the code as it is now. I have been able to run your notebook in HN using Spark and to produce a root file containing a subset of the histograms:

```{python}
# save histograms# save h 
c = ROOT.TCanvas();
outF = ROOT.TFile.Open("distributions_spark_other" + selected_diagonal + ".root", "recreate");

# Line 1700
hitDistDir = outF.mkdir("hit distributions");
ROOT.gDirectory = hitDistDir.mkdir("vertical, aligned, before selection");
histos[3].Write();
histos[2].Write();
histos[1].Write();
histos[4].Write();
histos[5].Write();
histos[6].Write();

ROOT.gDirectory = hitDistDir.mkdir("other");
```

This produces the following root file:

screen shot 2018-08-07 at 15 54 20


Are you trying to inspect the content of the root file right after writing an histogram (maybe from the Swan terminal)? If that's the case, you may need to write and close the root file before being able to see the written histogram:

```{python}
outF.Write()
outF.Close()
```

**Comment by JavierCVilla** [comment]
A couple of additional comments:

- I just compared the latter histogram with the equivalent one produced by the original analysis and the number of entries is quite different. I assume these differences are produced by the fact that we are currently considering a reduced number of input files, do not forget to replace it with the full list of input files.

- Could you please add a configuration file to this PR with the configuration you pasted here before? Since it is not stored as part of the notebook metadata, it would be convenient to save it in a file that everyone can check, a simple `.txt` file would be more than enough.

**Comment by mblaszkiewicz** [comment]
Ok, you're absolutely right, I downloaded it usually right away; thanks!

**Comment by mblaszkiewicz** [comment]
We just finished checking histograms one by one and we found out that there are differences between distributed and "sequential" execution (still using Spark but with 1 partition), e.g. histograms h_t_after in acceptance_correction had a difference in number of entries of about ~0,1% up to ~1% in the number of entries. 
When we compared the results of the notebook execution with only 1 partition to the python script (and original analysis), we found only minor differences in means, like 1.000e-316 and 5.000e-315. The only "more" major problem we saw was h_th_y_L_vs_th_x_L histogram, where numbers are similar but diagram looks different.

**Comment by JavierCVilla** [comment]
@mblaszkiewicz Please, have a look at the latest version of the code in [distributions.py](https://github.com/JavierCVilla/RDataFrame-Totem/blob/master/distributions.p), it seems that some of the most recent commits are not present in the notebook. 

For example, `h_th_y_L_vs_th_x_L` histogram produces the same summary numbers (entries, mean, std...) but the shape is difference due to the axis limits. This was fixed in commit [8824fa](https://github.com/JavierCVilla/RDataFrame-Totem/commit/8824fa28b9d57ce903e185c1070abcd8686a9140), namely is this [line](https://github.com/JavierCVilla/RDataFrame-Totem/blob/master/distributions.py#L506).

I would also expect some differences in `h_th_vs_phi_after` histogram, since the input columns are `k_phi` and `k_th`, which are not defined yet in this notebook. This was an issue introduced in one of the first versions of `distributions.py` and recently fixed [here](https://github.com/JavierCVilla/RDataFrame-Totem/commit/630d4255868a32eb3e9f4ebd94ffeac439920d93)

Regarding differences between distributed and 'sequential' execution for `h_t_after`, I don't have any clue what can be different, but I would check that you are using the latest version of the headers in `master`.

**Comment by mblaszkiewicz** [comment]
@JavierCVilla thanks a lot! I don't know how could I have overlooked that. If you had asked me before, I probably would have told you that it was already checked 

To make sure we are up to date in the notebook, I moved all list appends to the end and copied the distributions.py code once again

**Pull request merged**
