### PR TITLE
Complete distill

### PR DESCRIPTION
**Pull request by ciastkoMalinowe**
- Solved issue with run_num "Error in <TBranch::TLeaf>: data type for run_num/run_num/". 

- Added multithreading. 

- Data types in output root file are now compatible with original one.

No error for diagonal d45t_56b

### CODE REVIEW

**Review by JavierCVilla — CHANGES_REQUESTED** [review]
Hi @ciastkoMalinowe ,

Awesome! Thanks a lot for this PR!

Regarding your recent commit, can we instead use the same `prefix` we have in `distill.cc`? I just realized we are reading in a different way. I mean this one:

`root://eostotem.cern.ch//eos/totem/data/cmstotem/2015/90m/Totem/Ntuple/version2/4495/`

So that we ensure we also read remotely in this python version.

**Comment by ciastkoMalinowe** [comment]
Ok, the path which exists in master targets data on HN, where remote files from EOS are inaccessible. I will change the prefix to the same one which is in the original analysis but depends on where the code is to be run the prefix should be adjusted.

**Comment by JavierCVilla** [comment]
@ciastkoMalinowe Good to know that the remote access does not work in HN. I think we should prepare this `distill.py` script to be run in our comparison tests in LSF machines, so it should be equivalent to `distill.cc` in this sense.

**Comment by JavierCVilla** [comment]
@ciastkoMalinowe Finally, can you point this PR to `master` instead? I already merged `complete-distll` into `master`.

**Pull request merged**
